using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Data.DataModel;
using Data.Uow;
using Entity.DTOs;
using Microsoft.Extensions.Logging;

namespace TrashCollectionSystem.Controllers
{
    [Route("api/[controller]s")]
    [ApiController]
    public class ContainerController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<ContainerController> _logger;
        private readonly IMapper _mapper;

        public ContainerController(ILogger<ContainerController> logger, IUnitOfWork unitOfWork, IMapper mapper)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            //Getting all containers from database.
            var listOfContainers = await _unitOfWork.ContainerRepository.GetAll();
            if (listOfContainers is null)
            {
                return Ok("There is no containers.");
            }
            return Ok(listOfContainers);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(long id)
        {
            //getting the container whose id is equal to the parameter value.
            var container = await _unitOfWork.ContainerRepository.GetById(id);
            if (container is null)
            {
                return NotFound();
            }
            //Converting to entity from datamodel using AutoMapper.
            var entity = _mapper.Map<Container, ContainerViewModel>(container);

            return Ok(entity);
        }

        //Creating a container. For this method, ContainerViewModel is used. By this way, the user don't have to enter id value. Id value will be generated by database.
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] ContainerViewModel entity)
        {
            //Converting ContainerViewModel to Container model for adding to the database.
            var addedEntity = _mapper.Map<ContainerViewModel, Container>(entity);
            var response = await _unitOfWork.ContainerRepository.Add(addedEntity);
            _unitOfWork.Complete();
            if (response)
            {
                return Ok("Added");
            }
            return Ok("Failed");
        }

        //Updating a container. For this method, ContainerUpdateModel is used. By this way, the user can't change the VehicleId value.
        [HttpPut]
        public async Task<IActionResult> Update([FromBody] ContainerUpdateModel entity)
        {
            //Converting to container from containerupdatemodel using AutoMapper.
            var updatedEntity = _mapper.Map<ContainerUpdateModel, Container>(entity);
            updatedEntity.VehicleId = _unitOfWork.ContainerRepository.GetById(entity.Id).Result.VehicleId;
            var response = await _unitOfWork.ContainerRepository.Update(updatedEntity);
            _unitOfWork.Complete();
            return Ok();
        }

        //Deleting a container by just entering the id value.
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(long id)
        {
            var response = await _unitOfWork.ContainerRepository.Delete(id);
            _unitOfWork.Complete();
            if (response)
            {
                return Ok("Deleted.");
            }
            return Ok("Failed");
        }
    }
}
